name=input("hello! what is your name? ")
print(f"welcome to git hub {name}")
age=int(input("how old are you? "))
print(f"so you were born in {2021-age}")
for index, letter in enumerate(name):
    print(f"letter {index+1}: {letter}")
print(f"your name {len(name)} letters")
print("well done")
print("well done 2")
print("well done 3")
print("999")
print("888")
print("777")
